<?phpget_header();?>
<divclass="projets">
<?phpif(have_posts()):?>
<?phpwhile(have_posts()):the_post();?>
<articleclass="projet">
<?phpthe_post_thumbnail('thumbnail');?>
<h1class="title">
<ahref="<?phpthe_permalink();?>">
<?phpthe_title();?>
</a>
</h1>
<divclass="content">
<?phpthe_content();?>
</div>
</article>
<?phpendwhile;?>
<?phpendif;?>
</div>
<?phpget_footer();?>
